### ISSUE TITLE
breakages of rpm 4.13 boolean dependencies

### ISSUE THREAD

**Issue by XRevan86** [openSUSE/obs-service-format_spec_file#23]
rpm 4.13 (which found its way to Tumbleweed recently) has introduced a new feature: [boolean dependencies](http://rpm.org/user_doc/boolean_dependencies.html).
But format_spec_file (and https://github.com/openSUSE/spec-cleaner/issues/174) messes them up, turning
```
Requires: (foo and bar)
```
into
```
BuildRequires:  (foo
BuildRequires:  and
BuildRequires:  bar)
```

**Comment by bugfinder** [comment]
should already be fixed since commit edda1ae4db7e81096945fe4e4a4e57d9324262fa
