### ISSUE TITLE
URL in preamble should be defined as URL not Url

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/obs-service-format_spec_file#24]
As per poll on opensuse-packaging project https://doodle.com/poll/9y6gfunm8bm8cz3b

Counterpart change of spec-cleaner https://github.com/openSUSE/spec-cleaner/commit/a82a7330980afa8488d40c0827d7820762942ce7

**Comment by bugfinder** [comment]
see https://github.com/openSUSE/obs-service-format_spec_file/pull/37
