### ISSUE TITLE
update to License fails rpmlint

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/obs-service-format_spec_file#31]
When I tried to build 42.3's `intltool` package locally for a 42.3 maintenance update using `osc build`
it always failed with
`intltool.src: E: invalid-license (Badness: 100000) GPL-2.0-or-later`

It only worked with `osc revert *.spec ; osc build --no-service`

**Comment by coolo** [comment]
building against :Update? We put updated rpmlint in all channels
