### ISSUE TITLE
Clean up `\r` with spec-cleaner

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/obs-service-format_spec_file#33]
Original issue here https://github.com/openSUSE/osc/issues/647

I sometimes copied some build commands from GitHub or websites. The copied text may contains `\r` and some editors don't convert it (vim). When I run `osc build`, it will throw an error at `\r` (show as `^M` in vim) position.

Maybe `format_spec_file` can call `spec-cleaner` when preparing the spec file.

**Comment by coolo** [comment]
WIP
