### ISSUE TITLE
Update SUSE copyright string

### ISSUE THREAD

**Issue by ismail** [openSUSE/obs-service-format_spec_file#35]
Correct copyright string for SUSE is ```SUSE LLC``` which can be confirmed by visiting https://www.suse.com/c/news/suse-secures-openchain-certification-meeting-the-new-industry-benchmark-for-a-simplified-open-source-experience/

**Comment by bugfinder** [comment]
see https://github.com/openSUSE/obs-service-format_spec_file/pull/36
