### ISSUE TITLE
format_spec_file breaks topcomment package name

### ISSUE THREAD

**Issue by jengelh** [openSUSE/obs-service-format_spec_file#43]
Observed:
```
» cat qt6-coap.spec
Name:           qt6-coap%{?pkg_suffix}
» /usr/lib/obs/service/format_spec_file.files/prepare_spec qt6-coap.spec | head -n2
#
# spec file for package qt6
```

Expected:
```
# spec file for package qt6-coap
```

Version: obs-service-format_spec_file-20191114-1.3.noarch (openSUSE Tumbleweed du jour)

**Comment by coolo** [comment]
Could I please have the full spec file? And note that this package name in the comment is based on a very wild heuristic

**Comment by coolo** [comment]
```coolo@e138#qt6-coap>~/prod/obs-service-format_spec_file/prepare_spec qt6-coap.spec | head -n 10
#
# spec file for package qt6-coap%{?pkg_suffix}
#
# Copyright (c) 2021 SUSE LLC
```

Better? :)

**Comment by coolo** [comment]
This is what master does

**Comment by jengelh** [comment]
Full spec is https://build.opensuse.org/package/view_file/KDE:Qt:6.0/qt6-opcua/qt6-opcua.spec?expand=1

I can confirm 92427bcbd0854e5842399255728105faa71f14e2 fixes the issue. Could we have an updated obs-format-spec_file package for openSUSE? ;-) Thanks!

**Comment by coolo** [comment]
Talk to @DimStar77 - he keeps declining my package because of other people's packages :)
