### ISSUE TITLE
Deep recursion on subroutine "Parser::merge_comments" at /usr/lib/obs/service/format_spec_file.files/prepare_spec line 1044.

### ISSUE THREAD

**Issue by marxin** [openSUSE/obs-service-format_spec_file#47]
Likely also a recent change. Due to it one can see in: `devel:gcc/gcc11` unmerged `Copyright` in:

```
$ grep 'Copyright.*' cross-sparc-gcc11.spec
# Copyright (c) 2021 SUSE LLC
# Copyright (c) 2005 SUSE Linux AG, Nuernberg, Germany.
```

I'm pretty sure these used to be merge correctly.

**Comment by coolo** [comment]
I can't reproduce your Copyright merge problem. The deep recursion warning is just that: a warning - you get it if you reach level 100, which gcc spec files exceed easily.
