### ISSUE TITLE
License for Larceny scheme

### ISSUE THREAD

**Issue by owinebar** [openSUSE/obs-service-format_spec_file#57]
I'd like to import Larceny Scheme (https://github.com/larcenists/larceny) into an OBS package, but the license 
at https://github.com/larcenists/larceny/blob/master/COPYRIGHT appears to be idiosyncratic and does not directly correspond to an existing license.
Can someone review it and let me know if either it would be considered an instance of an existing entry or add a new entry for it?

**Comment by coolo** [comment]
I'm not a lawyer, but I see nothing problematic in this license. It's on the level of CC-BY-SA

**Comment by owinebar** [comment]
The main provisions look like a variant of the 3-clause BSD license to me (also not a lawyer), but with author/institution-specific requirements.  Then there's the additional licenses for pieces integrated from other authors, including one variant which is covered by the LGPL due to incorporated an LGPL licensed assembler (for the IA32 native backend).
I want to package the existing release, but then also create a fork to use an LLVM backend, since the author appears to have retired from computing (in public) for the last 5 years.

**Comment by coolo** [comment]
The license allows forks and from what I see you're free to relicense it as LGPL as long as you keep the copyright notices. But this has nothing to do with format_spec

**Comment by owinebar** [comment]
Maybe it's not clear, but the documentation for using OpenBuildService
states that using the public server requires distribution under an open
source license on the list here.
My question was, can the larceny license be added to the list so I can
distribute it as is?  I have no idea where else I would ask.

**Comment by owinebar** [comment]
I mean, it's bad form to claim to add restrictions to someone's software
just to package it. The author{s} made a point of keeping most of the
system unencumbered even by the LGPL.

**Comment by coolo** [comment]
You don't have to be correct in your spec file's license usage to use the build service - if the license is open source, it's fine. If it exists in SPDX doesn't matter for that. Use `Licence: SUSE-Permissive` in your spec file for now.

**Comment by owinebar** [comment]
Thanks!
